apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: issuer
spec:
  acme:
    email: demo@jetstack.io
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: issuer-letsencrypt-account-key-secret
    http01: {}