apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: certificate
spec:
  secretName: secret-www-demo-jetstack-net
  commonName: www.demo.jetstack.net
  dnsNames:
  - www.demo.jetstack.net
  issuerRef:
    name: issuer
    kind: Issuer
  acme:
    config:
    - http01:
        ingress: ingress
      domains:
      - www.demo.jetstack.net